// <auto-generated />
using System;
using Cotizador_Celebraciones.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cotizador_Celebraciones.Migrations
{
    [DbContext(typeof(Cotizador_CelebracionesContext))]
    [Migration("20190219182745_Lugar")]
    partial class Lugar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cotizador_Celebraciones.Models.Cotizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cliente");

                    b.Property<string>("Detalles");

                    b.Property<DateTime>("Fecha");

                    b.Property<DateTime>("Hora");

                    b.Property<string>("Lugar");

                    b.Property<string>("NombreEvento");

                    b.HasKey("Id");

                    b.ToTable("Cotizacion");
                });
#pragma warning restore 612, 618
        }
    }
}
